name: tester

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    outputs:
      should-run-tests: ${{ steps.changes.outputs.go == 'true' }}
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            go:
              - '**.go'
              - 'go.*'
              - '.github/workflows/test.yml'
  test:
    needs: [changes]
    if: github.event.pull_request.draft == false && ${{ needs.changes.outputs.should-run-tests == true }}
    name: runner / gotest
    runs-on: ubuntu-22.04
    container: ghcr.io/runatlantis/testing-env:latest
    steps:
      - run: echo ${{ needs.changes.outputs.should-run-tests }}
      - uses: actions/checkout@v3
      - run: make test-all
      - run: make check-fmt
      - run: 'echo "No build required"'

  skip-test:
    needs: [changes]
    if: github.event.pull_request.draft == false && ${{ needs.changes.outputs.should-run-tests == false }}
    name: runner / gotest
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ needs.changes.outputs.should-run-tests }}
      - run: 'echo "No build required"'
